---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Julian Schneider
-- Authors: Julian Schneider
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- Register map of the MIB: addresses, field positions and reset values of the AXI4-Lite registers.
-- Generated by tools/regmap.py from hdl/omap_mib/regs/omap_regs.yml, do not edit.
--
-- Documentation: hdl/omap_mib/docs/register_map.md

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;

---------------------------------------------------------------------------------------------------
-- Package Header
---------------------------------------------------------------------------------------------------
package omap_regs_pkg is

    -----------------------------------------------------------------------------------------------
    -- Identification
    -----------------------------------------------------------------------------------------------
    constant RegMapId_c : std_logic_vector(31 downto 0) := x"4F4D4101";

    -----------------------------------------------------------------------------------------------
    -- Register addresses (byte addresses)
    -----------------------------------------------------------------------------------------------
    constant RegId_c             : natural := 16#000#;
    constant RegGenerics_c       : natural := 16#004#;
    constant RegBuffers_c        : natural := 16#008#;
    constant RegTgtLa_c          : natural := 16#010#;
    constant RegTgtKey_c         : natural := 16#014#;
    constant RegTgtLast_c        : natural := 16#018#;
    constant RegTgtLastTid_c     : natural := 16#01C#;
    constant RegTgtLastAddr_c    : natural := 16#020#;
    constant RegTgtLastAddrExt_c : natural := 16#024#;
    constant RegTgtCntOk_c       : natural := 16#030#;
    constant RegTgtCntOk2_c      : natural := 16#034#;
    constant RegTgtCntHdr_c      : natural := 16#038#;
    constant RegTgtCntErr1_c     : natural := 16#03C#;
    constant RegTgtCntErr2_c     : natural := 16#040#;
    constant RegTgtCntErr3_c     : natural := 16#044#;
    constant RegTgtCntErr4_c     : natural := 16#048#;
    constant RegTgtCntErr5_c     : natural := 16#04C#;
    constant RegTgtCntErr6_c     : natural := 16#050#;
    constant RegIniTimeout_c     : natural := 16#060#;
    constant RegIniStatus_c      : natural := 16#064#;
    constant RegIniCnt1_c        : natural := 16#068#;
    constant RegIniCnt2_c        : natural := 16#06C#;
    constant RegIniCnt3_c        : natural := 16#070#;
    constant RegIniCnt4_c        : natural := 16#074#;
    constant RegPktCnt_c         : natural := 16#080#;
    constant RegEvents_c         : natural := 16#090#;
    constant RegIrqEn_c          : natural := 16#094#;
    constant RegIrqStatus_c      : natural := 16#098#;
    constant RegEccStatus_c      : natural := 16#0A0#;
    constant RegEccSelect_c      : natural := 16#0A4#;
    constant RegEccCount_c       : natural := 16#0A8#;
    constant RegEccInject_c      : natural := 16#0AC#;

    -----------------------------------------------------------------------------------------------
    -- WINDOW registers: address of instance n = Reg<Name>_c + n * RegWindowStride_c
    -----------------------------------------------------------------------------------------------
    constant RegWindowBase_c   : natural := 16#100#;
    constant RegWindowStride_c : natural := 16#010#;
    constant RegWinCtrl_c      : natural := 16#100#;
    constant RegWinBase_c      : natural := 16#104#;
    constant RegWinLast_c      : natural := 16#108#;
    constant RegWinCtrlOfs_c   : natural := 16#00#;
    constant RegWinBaseOfs_c   : natural := 16#04#;
    constant RegWinLastOfs_c   : natural := 16#08#;

    -----------------------------------------------------------------------------------------------
    -- Fields: bit of a one-bit field, lowest and highest bit of a wider field
    -----------------------------------------------------------------------------------------------

    constant IdIdLo_c : natural := 0;
    constant IdIdHi_c : natural := 31;

    constant GenericsTarget_c         : natural := 0;
    constant GenericsInitiator_c      : natural := 1;
    constant GenericsPassthrough_c    : natural := 2;
    constant GenericsExtAuth_c        : natural := 3;
    constant GenericsWindowsLo_c      : natural := 4;
    constant GenericsWindowsHi_c      : natural := 7;
    constant GenericsTransactionsLo_c : natural := 8;
    constant GenericsTransactionsHi_c : natural := 15;
    constant GenericsWordBytesLo_c    : natural := 16;
    constant GenericsWordBytesHi_c    : natural := 23;
    constant GenericsTgtAddrBytesLo_c : natural := 24;
    constant GenericsTgtAddrBytesHi_c : natural := 28;

    constant BuffersVerifyBytesLo_c : natural := 0;
    constant BuffersVerifyBytesHi_c : natural := 15;
    constant BuffersChunkBytesLo_c  : natural := 16;
    constant BuffersChunkBytesHi_c  : natural := 31;

    constant TgtLaLa0Lo_c   : natural := 0;
    constant TgtLaLa0Hi_c   : natural := 7;
    constant TgtLaLa1Lo_c   : natural := 8;
    constant TgtLaLa1Hi_c   : natural := 15;
    constant TgtLaLa0En_c   : natural := 16;
    constant TgtLaLa1En_c   : natural := 17;
    constant TgtLaDefLaEn_c : natural := 18;

    constant TgtKeyKeyLo_c : natural := 0;
    constant TgtKeyKeyHi_c : natural := 7;
    constant TgtKeyKeyEn_c : natural := 8;

    constant TgtLastStatusLo_c : natural := 0;
    constant TgtLastStatusHi_c : natural := 7;
    constant TgtLastInstrLo_c  : natural := 8;
    constant TgtLastInstrHi_c  : natural := 15;
    constant TgtLastIlaLo_c    : natural := 16;
    constant TgtLastIlaHi_c    : natural := 23;
    constant TgtLastReplied_c  : natural := 24;

    constant TgtLastTidTidLo_c : natural := 0;
    constant TgtLastTidTidHi_c : natural := 15;

    constant TgtLastAddrAddrLo_c : natural := 0;
    constant TgtLastAddrAddrHi_c : natural := 31;

    constant TgtLastAddrExtExtLo_c : natural := 0;
    constant TgtLastAddrExtExtHi_c : natural := 7;

    constant TgtCntOkWriteLo_c : natural := 0;
    constant TgtCntOkWriteHi_c : natural := 15;
    constant TgtCntOkReadLo_c  : natural := 16;
    constant TgtCntOkReadHi_c  : natural := 31;

    constant TgtCntOk2RmwLo_c     : natural := 0;
    constant TgtCntOk2RmwHi_c     : natural := 15;
    constant TgtCntOk2RepliesLo_c : natural := 16;
    constant TgtCntOk2RepliesHi_c : natural := 31;

    constant TgtCntHdrHdrCrcLo_c   : natural := 0;
    constant TgtCntHdrHdrCrcHi_c   : natural := 15;
    constant TgtCntHdrHdrShortLo_c : natural := 16;
    constant TgtCntHdrHdrShortHi_c : natural := 31;

    constant TgtCntErr1GeneralLo_c : natural := 0;
    constant TgtCntErr1GeneralHi_c : natural := 15;
    constant TgtCntErr1UnusedLo_c  : natural := 16;
    constant TgtCntErr1UnusedHi_c  : natural := 31;

    constant TgtCntErr2KeyLo_c     : natural := 0;
    constant TgtCntErr2KeyHi_c     : natural := 15;
    constant TgtCntErr2DataCrcLo_c : natural := 16;
    constant TgtCntErr2DataCrcHi_c : natural := 31;

    constant TgtCntErr3EarlyEopLo_c : natural := 0;
    constant TgtCntErr3EarlyEopHi_c : natural := 15;
    constant TgtCntErr3TooMuchLo_c  : natural := 16;
    constant TgtCntErr3TooMuchHi_c  : natural := 31;

    constant TgtCntErr4EepLo_c           : natural := 0;
    constant TgtCntErr4EepHi_c           : natural := 15;
    constant TgtCntErr4VerifyOverrunLo_c : natural := 16;
    constant TgtCntErr4VerifyOverrunHi_c : natural := 31;

    constant TgtCntErr5NotAuthLo_c   : natural := 0;
    constant TgtCntErr5NotAuthHi_c   : natural := 15;
    constant TgtCntErr5RmwLengthLo_c : natural := 16;
    constant TgtCntErr5RmwLengthHi_c : natural := 31;

    constant TgtCntErr6TlaLo_c     : natural := 0;
    constant TgtCntErr6TlaHi_c     : natural := 15;
    constant TgtCntErr6ReplyRxLo_c : natural := 16;
    constant TgtCntErr6ReplyRxHi_c : natural := 31;

    constant IniTimeoutTickCyclesLo_c : natural := 0;
    constant IniTimeoutTickCyclesHi_c : natural := 15;
    constant IniTimeoutTimeoutLo_c    : natural := 16;
    constant IniTimeoutTimeoutHi_c    : natural := 31;

    constant IniStatusOpenLo_c : natural := 0;
    constant IniStatusOpenHi_c : natural := 7;

    constant IniCnt1CmdSentLo_c : natural := 0;
    constant IniCnt1CmdSentHi_c : natural := 15;
    constant IniCnt1RepOkLo_c   : natural := 16;
    constant IniCnt1RepOkHi_c   : natural := 31;

    constant IniCnt2HdrErrLo_c  : natural := 0;
    constant IniCnt2HdrErrHi_c  : natural := 15;
    constant IniCnt2DataErrLo_c : natural := 16;
    constant IniCnt2DataErrHi_c : natural := 31;

    constant IniCnt3UnexpectedLo_c : natural := 0;
    constant IniCnt3UnexpectedHi_c : natural := 15;
    constant IniCnt3TimeoutLo_c    : natural := 16;
    constant IniCnt3TimeoutHi_c    : natural := 31;

    constant IniCnt4TidBusyLo_c : natural := 0;
    constant IniCnt4TidBusyHi_c : natural := 15;
    constant IniCnt4CmdRxLo_c   : natural := 16;
    constant IniCnt4CmdRxHi_c   : natural := 31;

    constant PktCntUserLo_c      : natural := 0;
    constant PktCntUserHi_c      : natural := 15;
    constant PktCntDiscardedLo_c : natural := 16;
    constant PktCntDiscardedHi_c : natural := 31;

    constant EventsPktDiscard_c : natural := 8;
    constant EventsEccDed_c     : natural := 7;
    constant EventsEccSec_c     : natural := 6;
    constant EventsIniTimeout_c : natural := 5;
    constant EventsIniError_c   : natural := 4;
    constant EventsIniReply_c   : natural := 3;
    constant EventsTgtCmd_c     : natural := 2;
    constant EventsTgtDiscard_c : natural := 1;
    constant EventsTgtError_c   : natural := 0;

    constant IrqEnEnableLo_c : natural := 0;
    constant IrqEnEnableHi_c : natural := 8;

    constant IrqStatusIrq_c : natural := 0;

    constant EccStatusDedLo_c : natural := 0;
    constant EccStatusDedHi_c : natural := 2;

    constant EccSelectChannelLo_c : natural := 0;
    constant EccSelectChannelHi_c : natural := 1;

    constant EccCountDedLo_c : natural := 16;
    constant EccCountDedHi_c : natural := 31;
    constant EccCountSecLo_c : natural := 0;
    constant EccCountSecHi_c : natural := 15;

    constant EccInjectDouble_c    : natural := 9;
    constant EccInjectSingle_c    : natural := 8;
    constant EccInjectChannelLo_c : natural := 0;
    constant EccInjectChannelHi_c : natural := 1;

    constant WinCtrlEnable_c       : natural := 0;
    constant WinCtrlRead_c         : natural := 1;
    constant WinCtrlWrite_c        : natural := 2;
    constant WinCtrlVerifiedOnly_c : natural := 3;
    constant WinCtrlRmw_c          : natural := 4;
    constant WinCtrlSingle_c       : natural := 5;
    constant WinCtrlBaseExtLo_c    : natural := 8;
    constant WinCtrlBaseExtHi_c    : natural := 15;
    constant WinCtrlLastExtLo_c    : natural := 16;
    constant WinCtrlLastExtHi_c    : natural := 23;

    constant WinBaseAddrLo_c : natural := 0;
    constant WinBaseAddrHi_c : natural := 31;

    constant WinLastAddrLo_c : natural := 0;
    constant WinLastAddrHi_c : natural := 31;

    -----------------------------------------------------------------------------------------------
    -- Reset values of the registers whose fields all have a fixed reset value
    -----------------------------------------------------------------------------------------------
    constant RegTgtCntOkReset_c   : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntOk2Reset_c  : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntHdrReset_c  : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntErr1Reset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntErr2Reset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntErr3Reset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntErr4Reset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntErr5Reset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegTgtCntErr6Reset_c : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIniCnt1Reset_c    : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIniCnt2Reset_c    : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIniCnt3Reset_c    : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIniCnt4Reset_c    : std_logic_vector(31 downto 0) := x"00000000";
    constant RegPktCntReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEventsReset_c     : std_logic_vector(31 downto 0) := x"00000000";
    constant RegIrqEnReset_c      : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccStatusReset_c  : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccSelectReset_c  : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccCountReset_c   : std_logic_vector(31 downto 0) := x"00000000";
    constant RegEccInjectReset_c  : std_logic_vector(31 downto 0) := x"00000000";

end package;
